version: "3"

services:
  tahsinus-next:
    container_name: tahsin.us-next
    image: tahsinature/next-tahsin-us:latest
    networks: [traefik]
    environment:
      DOPPLER_TOKEN: $DOPPLER_TOKEN_MY_PERSONAL
    labels:
      - traefik.enable=true
      - traefik.http.routers.tahsinus-back.rule=Host(`next.tahsin.us`)
      - traefik.http.services.tahsinus-back.loadbalancer.server.port=3000
      - traefik.http.routers.tahsinus-back.tls=true
      - traefik.http.routers.tahsinus-back.entrypoints=websecure
      - traefik.http.routers.tahsinus-back.tls.certresolver=myresolver

networks:
  traefik:
    external: true
