name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: cp .env.example .env.test

      - run: bun test:unit
